### ISSUE TITLE
BatList.modify_at instead of an array and a.(i) <- x ?

### ISSUE THREAD

**Issue by Naereen** [freuk/obandit#1]
Hi,
For example, here,
https://github.com/freuk/obandit/blob/18cf133099d0462ef498ddd76e9e0d612adfcd77/src/obandit.ml#L113
I wonder why you use this `BatList` module and a `modify_at` function (which cannot be in O(1) but is in O(n) if the list has n elements), instead of using a simple `int array` or `float array` and changing its i-th value with `a.(i) <- x`.
Thanks, I'm curious :smiley:.

**Comment by freuk** [comment]
Hey Lilian, because performance wasn't the concern.
If you have any serious use don't use the current opam release, there is a bugfix pending to be pushed. master is fine.

Ton travail est sympa, tu peux contacter @albietz qui travaille sur des choses similaires je pense, au vu de son dernier article et de ta librairie fraichement publiee.

**Comment by Naereen** [comment]
Hi,
OK, it makes sense, thanks for the quick reply. I don't plan on using `obandit` sorry.

Merci du pointeur, j'avais vu passé son dernier article mais sans relever que c'était quelqu'un d'Inria Grenoble :open_mouth: !
Bonne continuation :+1: !
